### PR TITLE
Update README.md and remove Cargo.lock from the project

### PR DESCRIPTION
**Pull request by VeroniDeev**
I update the README.md for the network and i remove the Cargo.lock file because this file is useless in an os project.

### CODE REVIEW

**Comment by VeroniDeev** [comment]
@Roxve

**Comment by Roxve** [comment]
YOOO MY BRO VERONI

**Comment by Roxve** [comment]
thank you so much!

**Comment by VeroniDeev** [comment]
ahahahaha wsp @Roxve

**Pull request merged**
